####################################################################
# _     ___  ____  ______   __  ____  _    _   _ ____              #
#| |   / _ \| __ )| __ ) \ / / |  _ \| |  | | | / ___|             #
#| |  | | | |  _ \|  _ \\ V /  | |_) | |  | | | \___ \             #
#| |__| |_| | |_) | |_) || |   |  __/| |__| |_| |___) |            #
#|_____\___/|____/|____/ |_|   |_|   |_____\___/|____/             # 
# ____              ____                  _                   _    #
#| __ ) _   _   _  |  _ \  __ _ _ __ _ __(_) ___  _ __   __ _| |_  #
#|  _ \| | | | (_) | | | |/ _` | '__| '__| |/ _ \| '_ \ / _` | __| #
#| |_) | |_| |  _  | |_| | (_| | |  | |  | | (_) | | | | (_| | |_  #
#|____/ \__, | (_) |____/ \__,_|_|  |_|  |_|\___/|_| |_|\__,_|\__| #
#       |___/                                                      #
####################################################################

#Support: If you need support add and dm me on Discord (@Darrion#5859)

##############################################
#  ___  _   _               _  ___ ___ _   _ #
# / _ \| \ | |             | |/ _ \_ _| \ | |#
#| | | |  \| |  _____   _  | | | | | ||  \| |#
#| |_| | |\  | |_____| | |_| | |_| | || |\  |#
# \___/|_| \_|          \___/ \___/___|_| \_|# 
##############################################
#xOnLogin (true/false) (If false, it is disabled)
#xLength in seconds (1000000) is infinite
#xLevel is what level of x the player gets
#xPermissionNeeded if true, it will require the permission, if false there is no requirement
#xOnLoginPermission custom permission node. This can be changed to what you want! (They can all even be the same)

SpeedOnLogin: false
SpeedPermissionNeeded: false
SpeedOnLoginPermission: 'login.speed'
SpeedLength: 1000000
SpeedLevel: 1

SaturationOnLogin: false
SaturationPermissionNeeded: false
SaturationLoginPermission: 'login.saturation'
SaturationLength: 1000000

NightVisionOnLogin: false
NightVisionPermissionNeeded: false
NightVisionLoginPermission: 'login.nightvision'
NightVisionLength: 1000000

#Allows a player to fly when they log in
FlyOnLogin: false
FlyPermissionNeeded: false
FlyOnLoginPermission: 'login.fly'

#Teleports a player to a location on login e.g. your spawn
#Yaw is horizontal direction
#Pitch is vertical direction
TeleportOnLogin: false
WorldOnLogin: 'world'
TeleportPermissionNeeded: false
TeleportOnLoginPermission: 'login.teleport'
X: 0
Y: 80
Z: 0
Yaw: 180
Pitch: 0

## Custom Join Item, this is what will open your Custom Item GUI.
## If a player right-clicks with this item, it'll open the GUI for custom items.
GUIItemOnLogin: true
GUIItemType: 'CHEST' # Use all caps, make sure it's a valid item type. 
GUIItemLore: '' # 
GUIItemName: '&eCustom Items'
GUIItemSlot: 9
PlayerCanMoveItem: false # Can move the item in their inventory, still can move if in creative.
PlayerCanDropItem: false # Can drop the item on the ground

#RunCommandsOnLogin (true/false) If true console will run commands on the login of a player
#commandsonjoin list format - 
#commandsonjoin:
# - firstcommandhere
# - secondcommandhere
#Use %player% to get the player's name
RunCommandsOnLogin: false
RunCommandsPermissionNeeded: false
RunCommandsOnLoginPermission: 'login.commands'
commandsonjoin:
 - say Welcome.
 - msg %player% Welcome to the server.
################################################################## 
# _          _     _             _____  __  __           _       #
#| |    ___ | |__ | |__  _   _  | ____|/ _|/ _| ___  ___| |_ ___ #
#| |   / _ \| '_ \| '_ \| | | | |  _| | |_| |_ / _ \/ __| __/ __|#
#| |__| (_) | |_) | |_) | |_| | | |___|  _|  _|  __/ (__| |_\__ \#
#|_____\___/|_.__/|_.__/ \__, | |_____|_| |_|  \___|\___|\__|___/#
#                        |___/                                   # 
##################################################################
#Double Jump. If a player has fly and doublejump, they will double jump instead of fly. (Except in creative or spectator)
# DoubleJumpOnlyInBorders: true/false. True will only let a player double jump inside the borders
DoubleJumpEnabled: true
DoubleJumpMultiplier: 1 #Setting this too high will crash the server. #5 at most is recommended
DoubleJumpOnlyInBorders: false #Put as false if you have borders disabled
DoubleJumpPermissionNeeded: false
DoubleJumpPermission: 'lobbyplus.doublejump'

##################################################################################
# ____                                       ____                _               #
#/ ___| _ __   __ ___      ___ __           | __ )  ___  _ __ __| | ___ _ __ ___ #
#\___ \| '_ \ / _` \ \ /\ / / '_ \   _____  |  _ \ / _ \| '__/ _` |/ _ \ '__/ __|#
# ___) | |_) | (_| |\ V  V /| | | | |_____| | |_) | (_) | | | (_| |  __/ |  \__ \#
#|____/| .__/ \__,_| \_/\_/ |_| |_|         |____/ \___/|_|  \__,_|\___|_|  |___/#
#      |_|                                                                       #
##################################################################################
#Make a square around spawn that players can not leave.
#If BordersEnabled is false, there will be no borders. If you want borders, configure and set to true.
#BorderWorld is the world with the X,Y,Z borders. **MAKE SURE THE WORLD IS CORRECT.**
#BorderOverridePermission can be changed to a custom permission. E.g. 'borders.ignore'
BordersEnabled: false
MobSpawningInBorders: false
ExplosionsInBorders: false
BorderWorld: 'world' #Make sure your world is correct!
BorderOverridePermission: 'borders.ignore'

#Square Border
#This is where you will setup your border coordinates.
#BorderLow is the lower coordinate of your pair.
#BorderHigh is the larger coordinate of your pair.
BorderLowX: -100
BorderHighX: 100

BorderLowY: 0
BorderHighY: 256

BorderLowZ: -100
BorderHighZ: 100

#BorderTp is the location a player will be teleported to after trying to leave the border. - E.g. Your spawn
#Yaw is horizontal direction
#Pitch is vertical direction
#BorderAttemptLeaveMsg is what will be said to the player when they try to leave the border.
BorderTpEnabled: false
BorderTpX: 0
BorderTpY: 80
BorderTpZ: 0
BorderTpYaw: 180 
BorderTpPitch: 0
BorderAttemptLeaveMsg: '&cYou cannot go there!'

#Border Protection are the events that can't happen.
#Allowx (true/false). If true, players can do x in the borders.
#BorderProtectionOverridePermission can be changed to a custom permission. E.g. 'bordersprotection.ignore'
AllowBreakBlocks: true
AttemptBreakBlockMsg: '&4&lHey! &7You cant break that here!'

AllowPlaceBlocks: true
AttemptPlaceBlockMsg: '&4&lHey! &7You cant place that here!'

AllowOpenChests: true
AttemptOpenChestMsg: '&4&lHey! &7You cant open that here!'

AllowClickFramesAndStands: true
AttemptItemFrameClickMsg: '&4&lHey! &7You cant click that here!'

#Players with BorderProtectionOverridePermission can still hit players when PvP is disabled!
AllowPvP: false
AllowMobsToHitPlayers: false
AllowPlayersHitMobs: true
AttemptPvPMsg: '&4&lHey! &7You cant PvP here!'

#This permission will allow a player to ignore the protections from the border.
#This will make it so players can still do these actions when disabled.
BorderProtectionOverridePermission: 'bordersprotection.ignore'

##################################################################################
#  ____          _                    __  __                                     #
# / ___|   _ ___| |_ ___  _ __ ___   |  \/  | ___  ___ ___  __ _  __ _  ___  ___ #
#| |  | | | / __| __/ _ \| '_ ` _ \  | |\/| |/ _ \/ __/ __|/ _` |/ _` |/ _ \/ __|#
#| |__| |_| \__ \ || (_) | | | | | | | |  | |  __/\__ \__ \ (_| | (_| |  __/\__ \#
# \____\__,_|___/\__\___/|_| |_| |_| |_|  |_|\___||___/___/\__,_|\__, |\___||___/#
#                                                                |___/           #
##################################################################################
#Max is 3 commands. May add more in the future, contact me if there should be.
#Send organized messages to players by commands (Color codes function)
# Format
# RegisteredCommands:
#  - /test
#  - /testtwo
# /testmessages: #Make sure you have the / in front of the command messages.
#  - '&dThis is the first message'
#  - ''
#  - '&bHere's the 3rd line.'


RegisteredCommands:
 - /test
 - /testtwo
 
/testmessages:
 - 'test'
 - 'this is line 2'
 - '&cLine 3'
/testtwomessages:
 - 'TestTwo'
 - 'You can customize this.'