name: LobbyPlus
version: 1.0
author: Darrionat
main: me.Darrionat.LobbyPlus.Main
commands:
  commandone:
    usage: </command>
  commandtwo:
    usage: </command>
  commandthree:
    usage: </command>
  lobbyplus:
    usage: </command>